#!/usr/bin/bash

if [ ! $(whoami) == "root" ]; then
    echo "Not root"
    exit 1
fi

if [ "$1" == "" ]; then
    echo "VM name not specified"
    exit 1
fi

sleep 3

systemctl stop display-manager
sleep 3

virsh start "$1"
sleep 5

# there are problems when a VM has a name that contains another VM name inside it (say, Windows10 and Windows10-Games)
while [[ $(virsh list) == *"$1"* ]]; do
    sleep 1
done

sleep 3

systemctl start display-manager
