#!/usr/bin/bash

# ensures this script is run by a regular user
if [ $(whoami) == "root" ]; then
    echo "Please run this script as a regular user, it needs to know what user to logoff"
else
    # sends the correct command
    sudo su -c "lsgp-helper $1 $(whoami) &"
fi
