#!/usr/bin/bash

# ensures this script is run by a regular user
if [ $(whoami) == "root" ]; then
    echo "Please run this script as a regular user, it should ask for permissions when appropriate"
    exit 1
fi

# sends the correct command
sudo su -c "lsgp-helper $1 $(whoami) | tee /tmp/lsgp-log.txt &"
