#!/usr/bin/bash

# virsh applies localization to returned values, this array should contain equivalents to 'running' in different languages
words=("running" "executando") # en-us, pt-br

# stops if not running as root
if [ ! $(whoami) == "root" ]; then echo "Not root"; exit 1; fi

# stops if the vm name was not specified
if [ "$1" == "" ]; then echo "VM name not specified"; exit 1; fi

sleep 5

# changes to another tty
chvt 3; sleep 1
pkill -KILL -u "$2"; sleep 1

# stops the display manager
systemctl stop display-manager
sleep 3

# changes the cpu frequency governor to performance
systemctl start perfgovernor

# starts the specified vm
virsh start "$1"

# waits some time before checking if its still running
sleep 3

# checks if the vm is still running every 5 seconds
while [ $(echo ${words[@]} | grep -o $(virsh list --all | grep " $1 " | awk '{ print $3}') | wc -w) == 1 ]; do sleep 5; done

# changes the cpu frequency governor back to powersave
systemctl stop perfgovernor

# waits 10 seconds for the gpu to be returned to the host
sleep 3

# starts the display manager again
systemctl start display-manager
